language: java

jdk:
  - oraclejdk9

install: true

script:
  - mvn --errors clean verify site
  - bash <(curl -s https://codecov.io/bash) -f com.io7m.junreachable.core/target/site/jacoco/jacoco.xml

notifications:
  irc: "chat.freenode.net#io7m"

